services:
  airflow-migrate:
    image: ${CI_REGISTRY_IMAGE}/airflow:${IMAGE_TAG}
    depends_on:
      postgres:
        condition: service_healthy
      sqitch-runner:
        condition: service_completed_successfully
    networks: [platform_network]
    environment:
      # Database
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    command: airflow db migrate

  airflow-webserver:
    image: ${CI_REGISTRY_IMAGE:-local}/airflow:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.airflow
      secrets:
        - pip_conf
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__API__BASE_URL=http://localhost:8080
    volumes:
      - dags_volume:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
