services:
  airflow-webserver:
    image: ${CI_REGISTRY_IMAGE:-local}/airflow:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.airflow
      secrets:
        - pip_conf
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - AIRFLOW__API__BASE_URL=http://localhost:8080
    volumes:
      - ${DAGS_DIR:-../dags}:/opt/airflow/dags
      - ../volumes/airflow_logs:/opt/airflow/logs