services:
  airflow-migrate:
    image: ${CI_REGISTRY_IMAGE}/airflow:${IMAGE_TAG}
    depends_on:
      timescaledb:
        condition: service_healthy
    networks: [platform_network]
    environment:
      # Database
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    command: airflow db migrate

  airflow-webserver:
    image: ${CI_REGISTRY_IMAGE:-local}/airflow:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.airflow
      secrets:
        - pip_conf
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__API__BASE_URL=http://localhost:8080
    volumes:
      - ${DAGS_DIR:-../dags}:/opt/airflow/dags
      - ../volumes/airflow_logs:/opt/airflow/logs