services:
  airflow-migrate:
    image: ${CI_REGISTRY_IMAGE}/airflow:${IMAGE_TAG}
    depends_on:
      timescaledb:
        condition: service_healthy
    command: airflow db migrate

  airflow-webserver:
    image: ${CI_REGISTRY_IMAGE}/airflow:${IMAGE_TAG}
    depends_on:
      airflow-migrate:
        condition: service_completed_successfully
    command: airflow api-server
    ports: ["8080:8080"]
    networks: [platform_network]
    environment:
      # Executor Config (Celery)
      - AIRFLOW__CELERY__BROKER_URL=${AIRFLOW__CELERY__BROKER_URL}
      - AIRFLOW__CELERY__RESULT_BACKEND=${AIRFLOW__CELERY__RESULT_BACKEND}
      # Airflow Core
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__EXECUTION_API_SERVER_URL=http://airflow-webserver:8080/execution/
      # Database
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      # Logging
      - AIRFLOW_CONN_MINIO_LOGS={"conn_type":"s3","login":"${MINIO_ROOT_USER}","password":"${MINIO_ROOT_PASSWORD}","extra":{"endpoint_url":"http://${MINIO_HOST}"}}
      # API
      - AIRFLOW__API__SECRET_KEY=${AIRFLOW__API__SECRET_KEY}
      # API Auth
      - AIRFLOW__API_AUTH__JWT_SECRET=${AIRFLOW_TMP_JWT_OVERRIDE}

      # Additional Env Vars for Services
      - S3_ACCESS_KEY=${MINIO_ROOT_USER}
      - S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - S3_ENDPOINT_URL=http://${MINIO_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

    deploy:
      replicas: 1
      restart_policy: { condition: on-failure, delay: 5s, max_attempts: 3, window: 2m }
      placement:
        constraints:
          - node.labels.role == public
      resources:
        reservations:
          cpus: "0.50"
          memory: 512M
        limits:
          cpus: "1.0"
          memory: 2G
      update_config: { parallelism: 1, order: start-first }
    ulimits:
      nofile: 16384
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://127.0.0.1:8080/api/v2/monitor/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "5" }


networks:
  platform_network: {}
