FROM apache/airflow:slim-3.1.0-python3.12

ARG AIRFLOW_VERSION=3.1.0
ARG PYTHON_VERSION=3.12
ARG CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

USER root

# Install system libraries
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgeos-dev libgomp1 libpq-dev libpq5 gcc libstdc++6 && \
    rm -rf /var/lib/apt/lists/*

# Install any Python deps
COPY requirements.txt /requirements.txt

# Copy DAGs & source code
COPY dags/ /opt/airflow/dags/

# Copy airflow config file
COPY airflow.cfg /opt/airflow/airflow.cfg

USER airflow
ENV PATH="/home/airflow/.local/bin:${PATH}"

RUN --mount=type=secret,id=pip_conf,target=/home/airflow/.pip/pip.conf,uid=50000,gid=0,mode=0400 \
    python -m pip install -U pip && \
    pip install --no-cache-dir -r /requirements.txt --constraint "${CONSTRAINT_URL}"
