FROM data-platform-api:latest

USER root

COPY ./tmp/ /opt/3phi-framework/
RUN ls /opt/3phi-framework/*.whl && \
    pip install --force-reinstall --no-cache-dir /opt/3phi-framework/3phi_framework-*.whl && \
    rm -r /opt/3phi-framework

