FROM airflow:latest

USER root

COPY ./tmp/ /opt/3phi-framework/
RUN if ls /opt/3phi-framework/*.whl 2>/dev/null; then \
        pip install /opt/3phi-framework/3phi_framework-*.whl \
        && rm -r /opt/3phi-framework; \
    fi

USER airflow