FROM apache/airflow:slim-2.11.0-python3.12

USER root

# Install system libraries
RUN apt-get update && apt-get install -y libgeos-dev libgomp1 libpq-dev libpq5 gcc

# Install any Python deps
COPY requirements.txt /requirements.txt

# read private index creds from a secret, not baked into the image
RUN --mount=type=secret,id=pip_conf,target=/etc/pip.conf \
    python -m pip install -U pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy DAGs & source code
COPY dags/ /opt/airflow/dags/

USER airflow

RUN pip install --no-cache-dir -r /requirements.txt

