services:

  redis:
    ports:
      - "6379:6379"

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8080:8080"
    volumes:
      - ./volumes/airflow_logs:/opt/airflow/logs

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - ./volumes/airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data

  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    volumes:
      - ./volumes/airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data

  dask-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dask
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - ./data:/opt/airflow/data

  dask-worker:
    build:
      context: .
      dockerfile: Dockerfile.dask
    volumes:
      - ./data:/opt/airflow/data
