secrets:
  pip_conf:
    file: ./pip.conf

services:
  redis:
    ports:
      - "6379:6379"

  airflow-scheduler:
    image: ${CI_REGISTRY_IMAGE:-local}/airflow:${IMAGE_TAG:-latest}
    volumes:
      - ${DAGS_DIR:-./dags}:/opt/airflow/dags
      - ./volumes/airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__API__BASE_URL=http://localhost:8080

  airflow-worker:
    image: ${CI_REGISTRY_IMAGE:-local}/airflow:${IMAGE_TAG:-latest}
    volumes:
      - ${DAGS_DIR:-./dags}:/opt/airflow/dags
      - ./volumes/airflow_logs:/opt/airflow/logs
      - ./data:/opt/airflow/data
    environment:
      - AIRFLOW__API__BASE_URL=http://localhost:8080

  dask-scheduler:
    image: ${CI_REGISTRY_IMAGE:-local}/dask:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dask
      secrets:
        - pip_conf
    environment:
      # Volume settings
      - DASK_TEMPORARY_DIRECTORY=/dask-scratch/scheduler
      - TMPDIR=/dask-scratch/scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - ./data:/opt/airflow/data
      - ./volumes/dask-scratch/scheduler:/dask-scratch/scheduler

  dask-worker:
    image: ${CI_REGISTRY_IMAGE:-local}/dask:${IMAGE_TAG:-latest}
    volumes:
      - ./data:/opt/airflow/data
      # - ./volumes/dask-scratch/worker:/dask-scratch/worker
