services:
  timescaledb:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1" ]
      interval: 2s
      timeout: 5s
      retries: 60
      start_period: 10s
    volumes:
      - local_timescale_data:/var/lib/postgresql/data

  minio:
    volumes:
      - local_minio_data:/data

  minio_createbuckets:
    image: alpine
    depends_on:
      - minio
    networks:
      - platform_network
    command: >
      sh -c "
      apk --no-cache add curl &&
      curl --progress-bar -L https://dl.min.io/aistor/mc/release/linux-arm64/mc --create-dirs -o ~/binaries/mc &&
      chmod +x ~/binaries/mc &&
      ~/binaries/mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      ~/binaries/mc mb minio/3phi && 
      ~/binaries/mc mb minio/airflow-logs
      "

  sqitch-runner:
    image: sqitch/sqitch
    working_dir: /sqitch
    environment:
      ROLE: threephi_db_user
      ROLE_PW: userpass
    depends_on:
      timescaledb:
        condition: service_healthy
    volumes:
      - ./data-platform-infrastructure/sqitch:/sqitch
    networks:
      - platform_network
    entrypoint: [ "bash", "-lc" ]
    command: >
      "ls && ./create-db-user.sh ${POSTGRES_HOST} ${POSTGRES_PORT} ${POSTGRES_USER} ${POSTGRES_PASSWORD} $${ROLE} $${ROLE_PW} ${POSTGRES_DB}
      && ./sqitch-deploy.sh ${POSTGRES_HOST}:${POSTGRES_PORT} ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${POSTGRES_DB}"

volumes:
  local_timescale_data: {}
  local_minio_data: {}
