-- Deploy 3phi-db:00_init to pg (fresh TimescaleDB-safe)

BEGIN;

-- Ensure TimescaleDB is installed before anything that depends on it
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- We won't drop/recreate the public schema; just ensure it exists.
CREATE SCHEMA IF NOT EXISTS public;
ALTER SCHEMA public OWNER TO postgres;
COMMENT ON SCHEMA public IS 'standard public schema';

-- Helper trigger function
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;
ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- =========================
-- Tables
-- =========================

CREATE TABLE public.file_index (
    id             uuid PRIMARY KEY,
    s3_key         text NOT NULL,
    dt             date NOT NULL,
    shard          integer NOT NULL,
    seq            bigint NOT NULL,
    ts_start       timestamptz NOT NULL,
    ts_end         timestamptz NOT NULL,
    rows           bigint NOT NULL,
    bytes          bigint NOT NULL,
    schema_version text NOT NULL,
    status         text NOT NULL,
    batch_id       uuid,                        -- NULLABLE so ON DELETE SET NULL can work
    ingest_file    text NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    committed_at   timestamptz,
    CONSTRAINT file_index_status_chk
       CHECK (status = ANY (ARRAY['staged','ready','deprecated','failed'])),
    CONSTRAINT file_index_dt_shard_seq_key
        UNIQUE (dt, shard, seq)
);

CREATE TABLE public.ingest_batch (
    id          uuid PRIMARY KEY,
    source_file text NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    status      text NOT NULL,
    error_log   text,
    stats_json  jsonb,
    run_id      text,
    CONSTRAINT ingest_batch_status_chk
     CHECK (status = ANY (ARRAY['in_progress','processed','failed'])),
    UNIQUE (source_file, run_id)
);

-- FK added after both tables exist (batch_id is nullable)
ALTER TABLE public.file_index
    ADD CONSTRAINT file_index_batch_fk
        FOREIGN KEY (batch_id) REFERENCES public.ingest_batch(id) ON DELETE SET NULL;

CREATE TABLE public.meter (
    id          text PRIMARY KEY,
    first_seen  timestamptz NOT NULL,
    last_seen   timestamptz NOT NULL,
    total_rows  bigint NOT NULL DEFAULT 0,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.hourly_measurements (
                                            meter_id   bigint NOT NULL,
                                            "timestamp" timestamptz NOT NULL,
                                            consumption real,
                                            production  real,
                                            PRIMARY KEY (meter_id, "timestamp")
);

CREATE TABLE public.meter_data (
    meter_id          bigint NOT NULL,
    "timestamp"       timestamptz NOT NULL,
    voltage_phase_1   numeric(10,2),
    voltage_phase_2   numeric(10,2),
    voltage_phase_3   numeric(10,2),
    p14_phase_1       double precision,
    p14_phase_2       double precision,
    p14_phase_3       double precision,
    p23_phase_1       double precision,
    p23_phase_2       double precision,
    p23_phase_3       double precision,
    q12_phase_1       double precision,
    q12_phase_2       double precision,
    q12_phase_3       double precision,
    q34_phase_1       double precision,
    q34_phase_2       double precision,
    q34_phase_3       double precision,
    u_thd_phase_1     double precision,
    u_thd_phase_2     double precision,
    u_thd_phase_3     double precision,
    i_thd_phase_1     double precision,
    i_thd_phase_2     double precision,
    i_thd_phase_3     double precision,
    PRIMARY KEY (meter_id, "timestamp")
);

CREATE TABLE public.workflow_states (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow    text NOT NULL UNIQUE,
    completed   boolean NOT NULL DEFAULT false,
    description text,
    updated_at  timestamp without time zone DEFAULT now()
);

-- =========================
-- Indexes
-- =========================
CREATE INDEX hourly_measurements_timestamp_idx ON public.hourly_measurements ("timestamp" DESC);
CREATE INDEX idx_file_ready_dt_shard_seq       ON public.file_index (dt, shard, seq DESC) WHERE (status = 'ready');
CREATE INDEX idx_file_ready_schema             ON public.file_index (schema_version)       WHERE (status = 'ready');
CREATE INDEX idx_file_ready_time_prune         ON public.file_index (dt, ts_start, ts_end) WHERE (status = 'ready');
CREATE INDEX meter_data_timestamp_idx          ON public.meter_data ("timestamp" DESC);

-- =========================
-- Timescale: turn the two tables into hypertables
-- (No manual insert_blocker triggers!)
-- =========================
SELECT create_hypertable('public.hourly_measurements', 'timestamp', if_not_exists => TRUE);
SELECT create_hypertable('public.meter_data', 'timestamp', if_not_exists => TRUE);

-- =========================
-- Triggers (your own only)
-- =========================
CREATE TRIGGER update_workflow_states_timestamp
    BEFORE UPDATE ON public.workflow_states
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================
-- Grants (these will error if the role doesn't exist)
-- =========================
REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT  ALL   ON SCHEMA public TO PUBLIC;
GRANT  ALL   ON SCHEMA public TO threephi_db_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.file_index          TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.hourly_measurements TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.ingest_batch        TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.meter               TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.meter_data          TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.workflow_states     TO threephi_db_user;

COMMIT;
