-- Deploy 3phi-db:00_init to pg

BEGIN;

-- We won't drop/recreate the schema; just ensure it exists.
CREATE SCHEMA IF NOT EXISTS :meta_schema;
ALTER SCHEMA :meta_schema OWNER TO postgres;
COMMENT ON SCHEMA :meta_schema IS 'standard metadata schema';

-- Helper trigger function
CREATE OR REPLACE FUNCTION :meta_schema.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;
ALTER FUNCTION :meta_schema.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';
SET default_table_access_method = heap;

-- Airflow Schema
CREATE SCHEMA IF NOT EXISTS airflow AUTHORIZATION postgres;
GRANT USAGE, CREATE ON SCHEMA airflow TO postgres;
ALTER ROLE postgres IN DATABASE "3phi-db" SET search_path = airflow, :meta_schema;

-- =========================
-- Tables
-- =========================

CREATE TABLE :meta_schema.file_index (
    id             uuid PRIMARY KEY,
    s3_key         text NOT NULL,
    dt             date NOT NULL,
    shard          integer NOT NULL,
    seq            bigint NOT NULL,
    ts_start       timestamptz NOT NULL,
    ts_end         timestamptz NOT NULL,
    rows           bigint NOT NULL,
    bytes          bigint NOT NULL,
    schema_version text NOT NULL,
    status         text NOT NULL,
    batch_id       uuid,                        -- NULLABLE so ON DELETE SET NULL can work
    ingest_file    text NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    committed_at   timestamptz,
    CONSTRAINT file_index_status_chk
       CHECK (status = ANY (ARRAY['staged','ready','deprecated','failed'])),
    CONSTRAINT file_index_dt_shard_seq_key
        UNIQUE (dt, shard, seq)
);

CREATE TABLE :meta_schema.ingest_batch (
    id          uuid PRIMARY KEY,
    source_file text NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    status      text NOT NULL,
    error_log   text,
    stats_json  jsonb,
    run_id      text,
    CONSTRAINT ingest_batch_status_chk
     CHECK (status = ANY (ARRAY['in_progress','processed','failed'])),
    UNIQUE (source_file, run_id)
);

-- FK added after both tables exist (batch_id is nullable)
ALTER TABLE :meta_schema.file_index
    ADD CONSTRAINT file_index_batch_fk
        FOREIGN KEY (batch_id) REFERENCES :meta_schema.ingest_batch(id) ON DELETE SET NULL;

CREATE TABLE :meta_schema.meter (
    id          bigint PRIMARY KEY,
    first_seen  timestamptz NOT NULL,
    last_seen   timestamptz NOT NULL,
    total_rows  bigint NOT NULL DEFAULT 0,
    updated_at  timestamptz NOT NULL DEFAULT now()
);


CREATE TABLE :meta_schema.workflow_states (
    id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    workflow    text NOT NULL UNIQUE,
    completed   boolean NOT NULL DEFAULT false,
    description text,
    updated_at  timestamp without time zone DEFAULT now()
);

-- =========================
-- Indexes
-- =========================

CREATE INDEX idx_file_ready_dt_shard_seq       ON :meta_schema.file_index (dt, shard, seq DESC) WHERE (status = 'ready');
CREATE INDEX idx_file_ready_schema             ON :meta_schema.file_index (schema_version)       WHERE (status = 'ready');
CREATE INDEX idx_file_ready_time_prune         ON :meta_schema.file_index (dt, ts_start, ts_end) WHERE (status = 'ready');

-- =========================
-- Triggers (your own only)
-- =========================
CREATE TRIGGER update_workflow_states_timestamp
    BEFORE UPDATE ON :meta_schema.workflow_states
    FOR EACH ROW EXECUTE FUNCTION :meta_schema.set_updated_at();

-- =========================
-- Grants (these will error if the role doesn't exist)
-- =========================
GRANT ALL ON SCHEMA :meta_schema TO threephi_db_user;

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE :meta_schema.file_index          TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE :meta_schema.ingest_batch        TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE :meta_schema.meter               TO threephi_db_user;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE :meta_schema.workflow_states     TO threephi_db_user;

COMMIT;
